### ISSUE TITLE
A flaw in the description of the JAXB dependency

### ISSUE THREAD

**Issue by earlspilner** [spring-petclinic/spring-petclinic-microservices#275]
Currently in `pom.xml` it is indicated that JAXB dependency is required since jdk-9 :
```
<!-- JAXB is required since Java 9 -->
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
</dependency>
```

But if we refer to the Eureka Server documentation, it says: 

> The JAXB modules which the Eureka server depends upon were removed in JDK 11. [Link](https://docs.spring.io/spring-cloud-netflix/reference/spring-cloud-netflix.html#spring-cloud-eureka-server:~:text=The%20JAXB%20modules%20which%20the%20Eureka%20server%20depends%20upon%20were%20removed%20in%20JDK%2011.)

It looks like in `pom.xml` it is worth pointing out that this is mandatory with jdk-11

**Comment by arey** [comment]
Hi @earlspilner 
The `JAXB` module have been removed from the JDK 9. See https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/
The JDK 9 is a non LTS version. Thus a lot of company upgrade from the Java 8 LTS version to the Java 11 LTS version.
That's why I suppose the `Eureka` documentation references the JDK 11.

**Comment by arey** [comment]
Please reopen if required
