### ISSUE TITLE
Add user friendly error when Java < 17 is used

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#280]
See https://github.com/spring-projects/spring-petclinic/commit/7b1abb3ca9a0a47afbcf4299638fc09e37b2405a

**Comment by AnkushThakur27** [comment]
@arey  can i pickup this ?

**Comment by arey** [comment]
Sure it is a good first issue

**Comment by AnkushThakur27** [comment]
@arey  Sorry to bother you but I am not able to push my code chages due to permission issue.  Can you add me as contributer ?

My User name : AnkushThakur27
email : aankushthakur27@gmail.com

20:44:16.918: [spring-petclinic-microservices] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/#280:refs/heads/feature/#280 --set-upstream
remote: Permission to spring-petclinic/spring-petclinic-microservices.git denied to AnkushThakur27.

**Comment by AnkushThakur27** [comment]
Hi @arey  Please review my pr : https://github.com/spring-petclinic/spring-petclinic-microservices/pull/286

**Comment by arey** [comment]
Close thanks to @AnkushThakur27
