### ISSUE TITLE
Migrate to dockerfile-maven or Google Jib

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-microservices#82]
Spotify recommand recommend that new projects use [dockerfile-maven](https://github.com/spotify/dockerfile-maven) instead of the old github.com/spotify/docker-maven-plugin.
We could also migrate to Google Jib: https://github.com/GoogleContainerTools/jib

**Comment by arey** [comment]
I've tried to migrate to Google Jib with the `jib-maven-pluginù but I'm not satisfied with it: the is no version of Dockerize for the `gcr.io/distroless/java` image and the `wait-for-it.sh` script is not working. Thus I have to use the `openjdk:8` Docker image. 

You could check my commit: https://github.com/arey/spring-petclinic-microservices/commit/1da92dd26c15e114b8ab66b6d19cf87aac877d82

**Comment by damc-dev** [comment]
Hey @arey, I checked out your commit on Windows 10 and the docker containers failed to start up due to this error:  /usr/bin/env: ‘bash\r’: No such file or directory.
Since git checks out files with the default line endings of the OS on Windows it defaults to CRLF.  I was able to use the dos2unix command to convert to unix line endings. after that the wait-for-it.sh worked as expected.

I have an interest in getting this merged into master, is there anything I can do to help?

**Comment by arey** [comment]
Hi @damc-dev I've added a `.gitattributes`file to my `feature/jib`branch: https://github.com/arey/spring-petclinic-microservices/blob/feature/jib/.gitattributes
It should solve your issue without having to use `dos2unix` tool.

It could be great to use `dockerize` instead of `wait-for-it.sh`. Microservices startup appears be more stable with it.

**Comment by arey** [comment]
Spring Boot layered jars is preferred to Google Jib: https://github.com/spring-petclinic/spring-petclinic-microservices/pull/155
